name: lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: setup python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Setup Poetry
      uses: snok/install-poetry@v1

    - name: Install
      run: |
        poetry install

    - name: run lint
      run: |
        poetry run tox -e lint
